server:
  port: 9002

spring:
  application:
    name: nacos-payment-service
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: 192.168.1.5:8387

management:
  endpoints:
    web:
      exposure:
        include: '*'
