server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
        namespace: 8292cb5a-51a3-49df-85a5-5e8c698de754  #注册进的命名空间
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        port: 8719

# 暴露监控端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
