server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: false   #不作为微服务注册进eureka
    service-url:
      #      defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
ribbon:
  ReadTimeout: 5000   # 指的是建立连接所用的时间，适用于网络状况正常的情况下，连段连接所用的时间
  ConnectTimeout: 5000  # 指的是建立连接后从服务器获取到可用的资源所用的时间

# Feign日志的级别
logging:
  level:
    # feign日志以什么级别监控哪个接口
    edu.hubu.springcloud.service.PaymentFeignService: debug

