server:
  port: 7001

spring:
  application:
    name: cloud-eureka-server7001

eureka:
  instance:
    #hostname: localhost  # eureka服务端实例名称
    hostname: eureka7001.com    # 在localhost配置了映射

  server:
    enable-self-preservation: true
  client:
    # 表示自己端就是注册中心
    fetch-registry: false
    # 表示不向注册中心注册自己
    register-with-eureka: false
    service-url:
#      defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/     # 单机版
    # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #单机没有修改host
