server:
  port: 8001


spring:
  application:
    name: cloud-provider-hystrix-payment

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源连接池
    driver-class-name: org.gjt.mm.mysql.Driver  #mysql驱动包
    url: jdbc:mysql://192.168.31.253:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      validation-query: select 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
       defaultZone: http://eureka7001.com:7001/eureka

#  instance:
#    instance-id: hystrix-payment8001
#    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.hubu.springcloud.entities