server:
  port: 3344

spring:
  application:
    name: cloud-config-center #注册进Eureka服务端的微服务名

  cloud:
    config:
      server:
        git:
          uri: git@github.com:HubuSugar/springcloud-config.git
          ####搜索目录
          search-paths:
            - springcloud-config
          default-label: main
      label: main

  # rabbitmq的地址
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# 暴露刷新碰撞点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
