server:
  port: 9003

spring:
  application:
    name: payment-provider-service

  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        server-addr: http://192.168.1.12:8387/

management:
  endpoints:
    web:
      exposure:
        include: '*'
