server:
  port: 8002

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源连接池
    driver-class-name: org.gjt.mm.mysql.Driver  #mysql驱动包
    url: jdbc:mysql://192.168.1.2:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      validation-query: select 1

mybatis:
  type-aliases-package: edu.hubu.springcloud.entities
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    # 表示自己是否注册进EurekaServer 默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka,http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
       defaultZone: http://eureka7001.com:7001/eureka


  # 修改主机名称
  instance:
    instance-id: payment8002
    prefer-ip-address: true   # 显示ip地址

